# Generated by Django 5.2.6 on 2026-05-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ['event_datetime']},
        ),
    ]
