# Generated by Django 5.2.1 on 2026-04-30 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_waldan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.AlterUniqueTogether(
            name='hasrelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hasrelationship',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='hasrelationship',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='orderpromotion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpromotion',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tcategory',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='torder',
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='usage_limit',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='tevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='order_waldan.event'),
        ),
        migrations.DeleteModel(
            name='EventArtist',
        ),
        migrations.DeleteModel(
            name='HasRelationship',
        ),
        migrations.DeleteModel(
            name='OrderPromotion',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
